#version 450

#extension GL_EXT_control_flow_attributes : require

#include "types.comp"

layout (push_constant) uniform parameter
{
    uint c_in;
    uint c_out;
    uint dst_w;
    uint dst_h;
    uint src_w;
    uint src_h;
    uint knl_w;
    uint knl_h;
    uint stride_x;
    uint stride_y;
} p;

layout (binding = 0) readonly buffer A {A_TYPE knl_data[];};
layout (binding = 1) readonly buffer B {B_TYPE src_data[];};
layout (binding = 2) writeonly buffer D {D_TYPE dst_data[];};

layout(local_size_x = 32, local_size_y = 8, local_size_z = 1) in;

void main() {
    uint batch = gl_WorkGroupID.z;
    uint spatial = gl_WorkGroupID.y * gl_WorkGroupSize.y + gl_LocalInvocationID.y;
    uint dst_c = gl_WorkGroupID.x * gl_WorkGroupSize.x + gl_LocalInvocationID.x;

    if (dst_c >= p.c_out || spatial >= p.dst_w * p.dst_h) {
        return;
    }

    uint dst_x = spatial % p.dst_w;
    uint dst_y = spatial / p.dst_w;

    uint src_base = batch * p.c_in * p.src_h * p.src_w;
    uint src_c_step = p.src_h * p.src_w;
    uint knl_c_step = p.c_out * p.knl_h * p.knl_w;

    uint off_x = dst_x % p.stride_x;
    uint src_x_start = dst_x / p.stride_x;

    uint off_y = dst_y % p.stride_y;
    uint src_y = dst_y / p.stride_y;
    
    FLOAT_TYPE sum = 0.0;
    for (uint knl_y = off_y; knl_y < p.knl_h; knl_y += p.stride_y) {
        if (src_y < p.src_h) { // && src_y >= 0
            uint src_x = src_x_start;
            for (uint knl_x = off_x; knl_x < p.knl_w; knl_x += p.stride_x) {
                if (src_x < p.src_w) { // && src_x >= 0
                    uint src_i = src_base + src_y * p.src_w + src_x;
                    uint knl_i = dst_c * p.knl_h*p.knl_w + knl_y * p.knl_w + knl_x;

                    [[unroll]]
                    for (uint c = 0; c < p.c_in; ++c) {
                        sum = fma(FLOAT_TYPE(src_data[src_i]), FLOAT_TYPE(knl_data[knl_i]), sum);
                        src_i += src_c_step;
                        knl_i += knl_c_step;
                    }
                }
                src_x--; // wraps when < 0
            }
        }
        src_y--; // wraps when < 0
    }

    uint dst_i = batch * (p.c_out * p.dst_h * p.dst_w)
               + dst_c * (p.dst_h * p.dst_w)
               + spatial;
    dst_data[dst_i] = D_TYPE(sum);
}
